const songs ={
    "Musicals":{
        "Rent":[
            {
                title: "Without You",
                lyrics: `Without you The ground thaws The rain falls The grass grows Without you The seeds root The flowers bloom The children play The stars gleam The poets dream The eagles fly Without you The earth turns The sun burns But I die Without you Without you The breeze warms The girl smiles The cloud moves Without you The tides change The boys run The oceans crash The crowds roar The days soar The babies cry Without you The moon glows The river flows But I die Without you The world revives Colors renew But I know blue only blue lonely blue within me blue Without you Without you The hand gropes The ear hears The pulse beats Without you The eyes gaze The legs walk The lungs breathe The mind churns The mind churns The heart yearns The heart yearns The tears dry Without you Life goes on But I'm gone Cause I die Without you Without you Without you Without you`
            },
            {
                title: "One Song Glory",
                lyrics: `One song Glory One song Before I go Glory one song to leave behind Find one song one last refrain Glory from the pretty boy front man Who wasted opportunity One song he had the world at his feet Glory in the eyes of a young girl A young girl Find glory Beyond the cheap colored lights One song before the sunsets Glory on another empty life Time flies Time dies Glory One blaze of glory One blaze of glory Glory Find glory In a song that rings true Truth like a blazing fire An eternal flame Find one song A song about love Glory From the soul of a young man A young man Find the one song Before the virus takes hold Glory Like a sunset One song To redeem this empty life Time flies And I don't need to endure anymore Time dies`
            }
        ],
        "Wicked":[
            {
                title: "The Wizard and I",
                lyrics: `Oh Miss Elphaba Many years I have waited For a gift like yours to appear Why I predict the Wizard Could make you his Magic grand vizier My dear my dear I'll write at once to the Wizard Tell him of you in advance With a talent like yours dear There is a defintish chance If you work as you should You'll be making good Did that really just happen Have I actually understood This weird quirk I've tried To suppress or hide Is a talent that could Help me meet the Wizard If I make good So I'll make good When I meet the Wizard Once I prove my worth And then I'll meet the Wizard What I've waited for since Since birth And with all his Wizard wisdom By my looks he won't be blinded Do you think the Wizard is dumb Or like Munchkins so small-minded No He'll say to me I see who you truly are A girl on whom I can rely And that's how we'll begin The Wizard and I Once I'm with the Wizard My whole life will change Cuz once you're with the Wizard No one thinks you're strange No father is not proud of you No sister acts ashamed And all of Oz has to love you When by the Wizard you're acclaimed And this gift or this curse I have inside Maybe at last I'll know why When we are hand in hand The Wizard and I And one day he'll say to me Elphaba A girl who is so superior Shouldn't a girl who's so good inside Have a matching exterior And since folks here to an absurd degree Seem fixated on your verdigris Would it be all right by you If I de-greenified you And though of course That's not important to me All right why not I'll reply Oh what a pair we'll be The Wizard and I Yes what a pair we'll be The Wizard and Unlimited My future is unlimited And I've just had a vision Almost like a prophecy I know it sounds truly crazy And true the vision's hazy But I swear someday there'll be A celebration throughout Oz That's all to do with me And I'll stand there with the Wizard Feeling things I've never felt And though I'd never show it I'd be so happy I could melt And so it will be And I'll want nothing else Till I die Held in such high esteem When people see me they will scream For half of Oz's favorite team The Wizard And I`
            }
        ]
    },

    "80s Songs":[
        {
            title: "Don't Stop Believin",
            lyrics: `Just a small town girl Livin in a lonely world She took the midnight train going anywhere Just a city boy Born and raised in South Detroit He took the midnight train going anywhere A singer in a smokey room A smell of wine and cheap perfume For a smile they can share the night It goes on and on and on and on Strangers waitin Up and down the boulevard Their shadows searchin in the night Streetlights people Livin just to find emotion Hidin somewhere in the night Workin hard to get my fill Everybody wants a thrill Payin anything to roll the dice Just one more time Some'll win some will lose Some are born to sing the blues Whoa the movie never ends It goes on and on and on and on Strangers waitin Up and down the boulevard Their shadows searchin in the night Streetlights people Livin just to find emotion Hidin somewhere in the night Don't stop believin Hold on to that feelin Streetlights people Don't stop believin Hold on Streetlights people Don't stop believin Hold on to that feelin Streetlights people`
        }
    ]
};